#!/bin/sh
# 
# 

if [ -d /data/data/com.termux/files/usr/etc ]; then
  conf_dir="/data/data/com.termux/files/usr/etc"
elif [ -d /usr/etc ]; then
  conf_dir="/usr/etc"
elif [ -d /etc ]; then
  conf_dir="/etc"
fi

if [ -e /usr/lib/sudo ]; then
	sudo python3 $conf_dir/debonair/dbnr.py
else
	python3 $conf_dir/debonair/dbnr.py
fi
exit
